// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyContacts.Data.DAL;

#nullable disable

namespace MyContacts.Migrations
{
    [DbContext(typeof(ContactContext))]
    [Migration("20240902140005_Initafaasdasdfa")]
    partial class Initafaasdasdfa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MyContacts.Data.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("varchar(1500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<int?>("ParentContactId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.HasKey("Id");

                    b.HasIndex("ParentContactId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("MyContacts.Data.Models.Contact", b =>
                {
                    b.HasOne("MyContacts.Data.Models.Contact", "ParentContact")
                        .WithMany("SubContacts")
                        .HasForeignKey("ParentContactId");

                    b.Navigation("ParentContact");
                });

            modelBuilder.Entity("MyContacts.Data.Models.Contact", b =>
                {
                    b.Navigation("SubContacts");
                });
#pragma warning restore 612, 618
        }
    }
}
